# ----------------------------------
# set up compilers
# ----------------------------------

FC 		= ifort
CC 		= icpc
CXX 		= icpc


# ----------------------------------
# compiler flags for OpenMP
# ----------------------------------

OMPFLAGS 	= -openmp


# ----------------------------------
# set up LLVM OpenMP runtime
# ----------------------------------

include Makefile.llvmomp

TARGET_LIBDIR=$(LLVM_OMP_ROOT)/lib/intel64
TARGET_LIB =$(TARGET_LIBDIR)/liboffload.so
LIBS += -Wl,-rpath=$(TARGET_LIBDIR) $(TARGET_LIB)
