ifndef LLVM_OMP_ROOT
  $(error You must define LLVM_OMP_ROOT so that the OpenMP library version providing the OMPT API can be found)
endif

# ----------------------------------
# set up OpenMP runtime
# ----------------------------------

LIB_DIR = $(LLVM_OMP_ROOT)/lib
LIB = $(LIB_DIR)/libomp.so


LIBS = -Wl,-rpath=$(LIB_DIR) $(LIB) -lm

# ----------------------------------
# include path for ompt.h and omp.h
# ----------------------------------
INCLUDES = -I$(LLVM_OMP_ROOT)/include
