# ----------------------------------
# set up compilers
# ----------------------------------

CC = clang -gdwarf-3
CXX = clang++ -gdwarf-3

# ----------------------------------
# compiler flags for OpenMP
# ----------------------------------

OMPFLAGS = -fopenmp

# ----------------------------------
# set up LLVM OpenMP runtime
# ----------------------------------

include Makefile.llvmomp
